file_format: "1"
id: hcid
name: Hcid
type: shield
url: https://github.com/nazzacode/zmk-config 
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - hcid_left
  - hcid_right