# manifest:
#   remotes:
#     - name: zmkfirmware
#       url-base: https://github.com/zmkfirmware
#   projects:
#     - name: zmk
#       remote: zmkfirmware
#       revision: main
#       import: app/west.yml
#   self:
#     path: config
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/artseyio
    - name: zmk-artsey
      url-base: https://github.com/artseyio
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: artsey
      import: app/west.yml
  self:
    path: config